const KEY='ministry-command-center-v1';
const sections={overview:{label:'Overview',icon:'▦'},outreach:{label:'Outreach',icon:'⌖'},people:{label:'People & teams',icon:'♙'},supplies:{label:'Supplies',icon:'▣'},prayer:{label:'Prayer follow-ups',icon:'♡'},finance:{label:'Giving & expenses',icon:'◈'}};
const titles={outreach:'Outreach plans',people:'People & teams',supplies:'Supplies & sack lunches',prayer:'Prayer follow-ups',finance:'Giving & expenses'};
const intros={outreach:'Plan worship, meals, and visits. Keep each location and next step together.',people:'Keep volunteer roles and availability in view. Only enter information you are comfortable storing on this device.',supplies:'See what is ready, what is needed, and what to bring to the next outreach.',prayer:'Remember who to check in with and when. Use initials or a general description for sensitive requests.',finance:'Record incoming gifts and ministry costs for your own working view. This is not an accounting ledger.'};
const fields={outreach:[['title','Plan title','text',true],['date','Date','date'],['location','Location','text'],['lead','Point person','text'],['notes','What needs to happen?','textarea']],people:[['title','Name or role','text',true],['role','Team / assignment','select',false,['Worship','Meals','Porch pickup drivers','Laundry & shopping drivers','Thursday donations helpers','Other']],['availability','Availability','text'],['notes','Notes','textarea']],supplies:[['title','Item','text',true],['quantity','Quantity','number'],['unit','Unit','text'],['status','Status','select',false,['Needed','Ready','Low']],['notes','Notes','textarea']],prayer:[['title','Name, initials, or topic','text',true],['date','Follow-up date','date'],['status','Status','select',false,['To follow up','In prayer','Followed up']],['notes','Brief note','textarea']],finance:[['title','Description','text',true],['kind','Type','select',false,['Donation','Expense']],['amount','Amount ($)','number'],['date','Date','date'],['notes','Notes','textarea']]};
let state;try{const saved=JSON.parse(localStorage.getItem(KEY));state=saved&&typeof saved==='object'&&saved.records? saved:{records:{outreach:[],people:[],supplies:[],prayer:[],finance:[]}}}catch{state={records:{outreach:[],people:[],supplies:[],prayer:[],finance:[]}}}for(const k of Object.keys(fields))if(!Array.isArray(state.records[k]))state.records[k]=[];
let page='overview',scope='all',search='',editId=null,entryType='outreach';const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{alert('This device could not save the change. Check available browser storage.');return false}}
function records(type){return state.records[type].filter(r=>scope==='all'||r.ministry===scope)}
function all(type){return type?records(type):Object.keys(fields).flatMap(k=>records(k).map(r=>({...r,_type:k})))}
function navigate(to){page=to;search='';$('#crumb').textContent=sections[to].label;$('#nav').innerHTML=Object.entries(sections).map(([key,v])=>`<button class="nav-item ${key===page?'active':''}" data-nav="${key}"><span class="nav-icon">${v.icon}</span>${v.label}</button>`).join('');closeMenu();render()}
function closeMenu(){$('.sidebar').classList.remove('open');$('#scrim').classList.remove('show')}
function tabs(){return `<div class="scope-tabs" role="group" aria-label="Ministry"><button data-scope="all" class="${scope==='all'?'active':''}">All ministries</button><button data-scope="Crown of Thorns" class="${scope==='Crown of Thorns'?'active':''}">Crown of Thorns</button><button data-scope="Return to Eden" class="${scope==='Return to Eden'?'active':''}">Return to Eden</button></div>`}
function head(label,subtitle,button){return `<div class="page-head"><div><span class="eyebrow">${esc(scope==='all'?'YOUR MINISTRIES':scope.toUpperCase())}</span><h1>${label}</h1><p class="sub">${subtitle}</p></div>${button||''}</div>`}
function addButton(type){return `<button class="button primary" data-add="${type}">＋ <span class="button-word">Add ${type==='people'?'person':type==='finance'?'entry':type==='supplies'?'item':type==='prayer'?'follow-up':'plan'}</span></button>`}
function meta(type,r){let parts=[r.ministry];if(r.date)parts.push(new Date(r.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}));if(type==='outreach'){if(r.location)parts.push(r.location);if(r.lead)parts.push(r.lead)}if(type==='people'){if(r.role)parts.push(r.role);if(r.availability)parts.push(r.availability)}if(type==='supplies'){if(r.quantity)parts.push(`${r.quantity} ${r.unit||''}`.trim())}if(type==='finance'&&r.amount)parts.push('$'+Number(r.amount).toFixed(2));return parts.map(esc).join(' · ')}
function item(type,r,compact=false){const status=r.complete?'Done':type==='supplies'?(r.status||'Needed'):type==='prayer'?(r.status||'To follow up'):type==='finance'?(r.kind||'Expense'):'Open';return `<div class="record"><div><strong>${esc(r.title)}</strong><small>${meta(type,r)}</small>${!compact&&r.notes?`<p>${esc(r.notes)}</p>`:''}</div><div class="record-actions"><span class="pill ${r.complete||status==='Ready'||status==='Followed up'?'done':status==='Needed'||status==='Low'?'high':''}">${esc(status)}</span>${!compact?`<button class="tiny" data-edit="${type}:${r.id}">Edit</button><button class="tiny" data-toggle="${type}:${r.id}">${r.complete?'Reopen':'Done'}</button>`:''}</div></div>`}
function empty(type){return `<div class="empty">No ${type==='finance'?'entries':type==='people'?'people':type==='prayer'?'follow-ups':type==='supplies'?'supplies':'plans'} yet for this view.<br>Add one to start keeping track.</div>`}
function overview(){const items=all();const open=items.filter(r=>!r.complete);const planned=all('outreach').filter(r=>!r.complete);const needed=all('supplies').filter(r=>!r.complete&&r.status!=='Ready');const follow=all('prayer').filter(r=>!r.complete&&r.status!=='Followed up');const finance=all('finance');const gifts=finance.filter(r=>r.kind==='Donation').reduce((n,r)=>n+Number(r.amount||0),0);const expenses=finance.filter(r=>r.kind==='Expense').reduce((n,r)=>n+Number(r.amount||0),0);return `<div class="page">${head('Good to see you, Mike.','A clear view of what needs care next.',addButton('outreach'))}${tabs()}<div class="stats"><div class="stat"><div class="label">Outreach plans</div><strong>${planned.length}</strong><small>Still open</small></div><div class="stat"><div class="label">Supplies needed</div><strong>${needed.length}</strong><small>Items to gather</small></div><div class="stat"><div class="label">Prayer follow-ups</div><strong>${follow.length}</strong><small>People or requests</small></div><div class="stat"><div class="label">Open items</div><strong>${open.length}</strong><small>Across this view</small></div></div><div class="grid"><div><div class="panel"><div class="panel-head"><h2>Upcoming outreach</h2><button class="text-link" data-nav="outreach">View all →</button></div>${planned.length?planned.sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).slice(0,4).map(r=>item('outreach',r,true)).join(''):empty('outreach')}</div><div class="panel"><div class="panel-head"><h2>Needs attention</h2></div>${[...needed.map(r=>({...r,_type:'supplies'})),...follow.map(r=>({...r,_type:'prayer'}))].slice(0,5).map(r=>item(r._type,r,true)).join('')||'<div class="empty">No supply needs or prayer follow-ups recorded yet.</div>'}</div></div><div><div class="feature"><span class="eyebrow">NEXT OUTREACH</span><h2>Make the next step simple.</h2><p>Set a place and time, note who is helping, then gather what the team needs.</p><button class="button" data-add="outreach">Plan an outreach ↗</button></div><div class="panel"><div class="panel-head"><h2>Quick add</h2></div><div class="quick-grid"><button class="quick" data-add="supplies"><span>▣</span><strong>Supply need</strong></button><button class="quick" data-add="people"><span>♙</span><strong>Team member</strong></button><button class="quick" data-add="prayer"><span>♡</span><strong>Prayer follow-up</strong></button><button class="quick" data-add="finance"><span>◈</span><strong>Gift or expense</strong></button></div></div><div class="panel"><div class="panel-head"><h2>Working balance</h2></div><div class="record"><div><strong>Recorded gifts</strong><small>$${gifts.toFixed(2)}</small></div></div><div class="record"><div><strong>Recorded expenses</strong><small>$${expenses.toFixed(2)}</small></div></div><p class="muted-note">Only entries you add here are counted. This is a planning view, not a bank balance.</p></div></div></div></div>`}
function section(type){const rs=records(type).filter(r=>(r.title+' '+(r.notes||'')+' '+(r.location||'')).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.complete-b.complete)||((a.date||'9999').localeCompare(b.date||'9999')));return `<div class="page">${head(titles[type],type==='finance'?'A simple working record for your ministry.':'Keep the next steps in one place.',addButton(type))}${tabs()}<p class="section-intro">${intros[type]}</p>${type==='prayer'||type==='people'?'<div class="notice">This version stores entries in this browser on this device. Avoid private addresses, sensitive stories, or confidential contact details.</div>':''}<div class="filterline"><input id="search" type="search" placeholder="Search ${type==='finance'?'entries':'records'}" value="${esc(search)}" aria-label="Search records"><span class="muted-note">${rs.length} ${rs.length===1?'record':'records'}</span></div><div class="panel list-panel"><div class="panel-head"><h2>${titles[type]}</h2></div>${rs.length?rs.map(r=>item(type,r)).join(''):empty(type)}</div></div>`}
function render(){ $('#content').innerHTML=page==='overview'?overview():section(page); }
function fieldHtml([key,label,type,required,options],r){const val=esc(r?.[key]??'');const id='field-'+key;if(type==='textarea')return `<label class="field" for="${id}">${label}<textarea id="${id}" name="${key}">${val}</textarea></label>`;if(type==='select')return `<label class="field" for="${id}">${label}<select id="${id}" name="${key}">${options.map(o=>`<option ${o===r?.[key]?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;return `<label class="field" for="${id}">${label}<input id="${id}" name="${key}" type="${type}" ${required?'required':''} ${type==='number'?'min="0" step="any"':''} value="${val}"></label>`}
function openForm(type,id){entryType=type;editId=id||null;const r=id?state.records[type].find(x=>x.id===id):null;$('#dialogKicker').textContent=editId?'EDIT RECORD':'NEW RECORD';$('#dialogTitle').textContent=editId?'Edit '+(type==='people'?'person':'entry'):'Add '+(type==='people'?'a person':type==='outreach'?'an outreach plan':type==='supplies'?'a supply item':type==='prayer'?'a follow-up':'a gift or expense');$('#formFields').innerHTML=`<label class="field" for="ministry">Ministry<select id="ministry" name="ministry"><option ${r?.ministry==='Crown of Thorns'||(!r&&scope!=='Return to Eden')?'selected':''}>Crown of Thorns</option><option ${r?.ministry==='Return to Eden'||(!r&&scope==='Return to Eden')?'selected':''}>Return to Eden</option></select></label>`+fields[type].map(f=>fieldHtml(f,r)).join('');$('#entryDialog').showModal();$('#formFields input')?.focus()}
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));if(editId){const idx=state.records[entryType].findIndex(r=>r.id===editId);if(idx>=0)state.records[entryType][idx]={...state.records[entryType][idx],...values}}else state.records[entryType].push({...values,id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),complete:false});if(save()){$('#entryDialog').close();render()}});
$('#content').addEventListener('click',e=>{const add=e.target.closest('[data-add]'),nav=e.target.closest('[data-nav]'),sc=e.target.closest('[data-scope]'),edit=e.target.closest('[data-edit]'),toggle=e.target.closest('[data-toggle]');if(add)openForm(add.dataset.add);else if(nav)navigate(nav.dataset.nav);else if(sc){scope=sc.dataset.scope;render()}else if(edit){const [type,id]=edit.dataset.edit.split(':');openForm(type,id)}else if(toggle){const [type,id]=toggle.dataset.toggle.split(':');const r=state.records[type].find(x=>x.id===id);if(r){r.complete=!r.complete;if(save())render()}}});
$('#content').addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;const start=e.target.selectionStart;const input=e.target;const pageHtml=section(page);$('#content').innerHTML=pageHtml;const next=$('#search');next.focus();next.setSelectionRange(start,start)}});
$('#nav').addEventListener('click',e=>{const btn=e.target.closest('[data-nav]');if(btn)navigate(btn.dataset.nav)});$('#menu').addEventListener('click',()=>{$('.sidebar').classList.add('open');$('#scrim').classList.add('show')});$('#scrim').addEventListener('click',closeMenu);$('#closeDialog').addEventListener('click',()=>$('#entryDialog').close());$('#cancelDialog').addEventListener('click',()=>$('#entryDialog').close());$('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});navigate('overview');
